<?php

namespace ContainerXD2xciT;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAppCommandGeneratePayrollDatesCommand_LazyService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.App\Command\AppCommandGeneratePayrollDatesCommand.lazy' shared service.
     *
     * @return \Symfony\Component\Console\Command\LazyCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/Command.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/LazyCommand.php';

        return $container->privates['.App\\Command\\AppCommandGeneratePayrollDatesCommand.lazy'] = new \Symfony\Component\Console\Command\LazyCommand('AppCommandGeneratePayrollDatesCommand', [], 'Add a short description for your command', false, #[\Closure(name: 'App\\Command\\AppCommandGeneratePayrollDatesCommand')] function () use ($container): \App\Command\AppCommandGeneratePayrollDatesCommand {
            return ($container->privates['App\\Command\\AppCommandGeneratePayrollDatesCommand'] ?? $container->load('getAppCommandGeneratePayrollDatesCommandService'));
        });
    }
}
