<?php

namespace ContainerXD2xciT;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAppCommandGeneratePayrollDatesCommandService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Command\AppCommandGeneratePayrollDatesCommand' shared autowired service.
     *
     * @return \App\Command\AppCommandGeneratePayrollDatesCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/Command.php';
        include_once \dirname(__DIR__, 4).'/src/Command/AppCommandGeneratePayrollDatesCommand.php';

        $container->privates['App\\Command\\AppCommandGeneratePayrollDatesCommand'] = $instance = new \App\Command\AppCommandGeneratePayrollDatesCommand();

        $instance->setName('AppCommandGeneratePayrollDatesCommand');
        $instance->setDescription('Add a short description for your command');

        return $instance;
    }
}
