<?php

namespace ContainerXD2xciT;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getGeneratePayrollDatesCommandService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Command\GeneratePayrollDatesCommand' shared autowired service.
     *
     * @return \App\Command\GeneratePayrollDatesCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/Command.php';
        include_once \dirname(__DIR__, 4).'/src/Command/GeneratePayrollDatesCommand.php';
        include_once \dirname(__DIR__, 4).'/src/Service/PayrollDateGenerator.php';

        $container->privates['App\\Command\\GeneratePayrollDatesCommand'] = $instance = new \App\Command\GeneratePayrollDatesCommand(new \App\Service\PayrollDateGenerator());

        $instance->setName('app:generate-payroll-dates');
        $instance->setDescription('Generates payroll dates for the rest of the current year and writes them to a CSV file');

        return $instance;
    }
}
