<?php

namespace ContainerPNKdA1V;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getGeneratePayrollDatesCommand_LazyService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.App\Command\GeneratePayrollDatesCommand.lazy' shared service.
     *
     * @return \Symfony\Component\Console\Command\LazyCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/Command.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/LazyCommand.php';

        return $container->privates['.App\\Command\\GeneratePayrollDatesCommand.lazy'] = new \Symfony\Component\Console\Command\LazyCommand('app:generate-payroll-dates', [], 'Generates payroll dates for the rest of the current year and writes them to a CSV file', false, #[\Closure(name: 'App\\Command\\GeneratePayrollDatesCommand')] function () use ($container): \App\Command\GeneratePayrollDatesCommand {
            return ($container->privates['App\\Command\\GeneratePayrollDatesCommand'] ?? $container->load('getGeneratePayrollDatesCommandService'));
        });
    }
}
