<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerPNKdA1V\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerPNKdA1V/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerPNKdA1V.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerPNKdA1V\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerPNKdA1V\App_KernelDevDebugContainer([
    'container.build_hash' => 'PNKdA1V',
    'container.build_id' => '5ea05eab',
    'container.build_time' => 1746818316,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerPNKdA1V');
